/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//-------------------------------------------------------------------=FOUR LED BLINK----------------------------------------------------------------------------------------------------
#include <stdint.h>
#include <stm32f407xx.h>
#include <stm32f407xx_GPIO_driver.h>


int main(void){
	GPIO_Handle_t SENSOR, LED, LED1, LED2;
			LED.pGPIOx =GPIOD;
			LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
			LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
			LED.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
			LED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
			LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;


			LED1.pGPIOx =GPIOD;
			LED1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
			LED1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
			LED1.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
			LED1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
			LED1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

			LED2.pGPIOx = GPIOA;
//			LED2.GPIO_PinConfig.GPIO_PinNumber =


			SENSOR.pGPIOx = GPIOA;
			SENSOR.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_10;
			SENSOR.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;



			GPIO_Init(&LED);
			GPIO_Init(&SENSOR);

			GPIO_WriteToOutputPin(GPIOD, 13, 1);

			while(1){

				GPIO_WriteToOutputPin(GPIOD, 12, 0);
				GPIO_WriteToOutputPin(GPIOD, 13, 1);
				if(GPIO_ReadFromInputPin(GPIOA, 10) == 0){
					GPIO_WriteToOutputPin(GPIOD, 13, 0);
					GPIO_WriteToOutputPin(GPIOD, 12, 1);


				}



			}


}



























//void delay(){
//	for(int i=0; i<100000; i++){
//
//	}
//}
//
//
//int main(void){
//	GPIO_Handle_t LED1, LED2, LED3, LED4;
//	LED1.pGPIOx= GPIOD;
//	LED1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
//	LED1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
//	LED1.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	LED1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
//	LED1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
//
//	LED2.pGPIOx= GPIOD;
//	LED2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
//	LED2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
//	LED2.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	LED2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
//	LED2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
//
//	LED3.pGPIOx= GPIOB;
//	LED3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
//	LED3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
//	LED3.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	LED3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
//	LED3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
//
//	LED4.pGPIOx= GPIOC;
//	LED4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
//	LED4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
//	LED4.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	LED4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
//	LED4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
//
//
//
//	GPIO_Init(&LED1);GPIO_Init(&LED2);GPIO_Init(&LED3);GPIO_Init(&LED4);
//
//	while(1){
////		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, ENABLE);
////		GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_14, ENABLE);
////		GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_13, ENABLE);
//		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, ENABLE);
//
//
//				}
//
//
//
//
//}

//--------------------------------------------------------------------- LED BLINK WITH USER BUTTON IT-------------------------------------------------------------------------------------
//#include <stdint.h>
//#include <stm32f407xx.h>
//#include <stm32f407xx_GPIO_driver.h>
//
//int main(void){
//	GPIO_Handle_t LED;
//	LED.pGPIOx = GPIOD;
//	LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
//	LED.GPIO_PinConfig.GPIO_PinMode =GPIO_MODE_OUT;
//	LED.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	LED.GPIO_PinConfig.GPIO_PinPuPdControl =GPIO_NO_PUPD;
//	LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
//
//	GPIO_Handle_t BUTTON;
//	BUTTON.pGPIOx = GPIOA;
//	BUTTON.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_0;
//	BUTTON.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_IN;
//
//
//	GPIO_Init(&LED);
//	GPIO_Init(&BUTTON);
//
//	while(1){
//		if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0)){
//		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, ENABLE);}
//		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, DISABLE);
//
//	}
//
//}
